trigger:
- main

pool:
  name: vmss

variables:
  imageName: 'prime-api'
  acrName: 'andreikubetestassignmentacr.azurecr.io'
  aksCluster: 'aks-cluster'
  resourceGroup: 'aks-rg'
  kubernetesNamespace: 'default'

steps:
- script: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && sudo chmod 777 /var/run/docker.sock
  displayName: Install Docker

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: $(acrName)
    repository: $(imageName)
    dockerfile: './src/prime-api/Dockerfile'
