trigger:
- main

pool:
  name: vmss

variables:
  imageName: 'prime-api'
  acrName: 'andreikubetestassignmentacr.azurecr.io'
  aksCluster: 'aks-cluster'
  resourceGroup: 'cluster'
  subscriptionId: 'e07f1145-7d1f-40d9-9d15-eda1488aef3a'

steps:
- script: |
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce
    sudo systemctl enable docker
    sudo systemctl start docker
    sudo chmod 777 /var/run/docker.sock
  displayName: Install Docker

- script: |
    sudo apt-get -y install zip
  displayName: Install zip

- task: HelmInstaller@1
  displayName: Install Helm
  inputs:
    helmVersionToInstall: 'latest'

- script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: Install Azure CLI

- script: |
    sudo apt-get update
    sudo apt-get install -y netcat
  displayName: 'Install netcat'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: $(acrName)
    repository: $(imageName)
    dockerfile: './src/prime-api/Dockerfile'
    tags: $(Build.BuildId)

- task: Kubernetes@1
  displayName: Login to Kubernetes
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(subscriptionId)
    azureResourceGroup: $(resourceGroup)
    kubernetesCluster: $(aksCluster)
    command: login

- task: HelmDeploy@1
  displayName: 'Deploy Helm chart'
  inputs:
    azureSubscription: $(subscriptionId)
    azureResourceGroup: $(resourceGroup)
    kubernetesCluster: $(aksCluster)
    namespace: default
    command: 'upgrade'
    releaseName: prime-api
    chartType: 'FilePath'
    chartPath: ./charts/prime-api
    overrideValues: |
      image.tag=$(Build.BuildId)
    waitForCompletion: false
    install: true

- script: |
    chmod +x ./scripts/check-deployment.sh
    ./scripts/check-deployment.sh
  displayName: 'Check helm is deployed and port is open'