trigger:
- main

pool:
  name: vmss

variables:
  imageName: 'prime-api'
  acrName: 'andreikubetestassignmentacr.azurecr.io'
  aksCluster: 'aks-cluster'
  resourceGroup: 'cluster'
  subscriptionId: 'e07f1145-7d1f-40d9-9d15-eda1488aef3a'

steps:
- script: |
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce
    sudo systemctl enable docker
    sudo systemctl start docker
    sudo chmod 777 /var/run/docker.sock
  displayName: Install Docker

- script: |
    sudo apt-get -y install zip
  displayName: Install zip

- task: HelmInstaller@1
  displayName: Install Helm
  inputs:
    helmVersionToInstall: 'latest'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: $(acrName)
    repository: $(imageName)
    dockerfile: './src/prime-api/Dockerfile'
    tags: $(Build.BuildId)

- task: Kubernetes@1
  displayName: Login to Kubernetes
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: $(subscriptionId)
    azureResourceGroup: $(resourceGroup)
    kubernetesCluster: $(aksCluster)
    command: login

- task: HelmDeploy@1
  displayName: 'Deploy Helm chart'
  inputs:
    azureSubscription: $(subscriptionId)
    azureResourceGroup: $(resourceGroup)
    kubernetesCluster: $(aksCluster)
    namespace: default
    command: 'upgrade'
    releaseName: prime-api
    chartType: 'FilePath'
    chartPath: ./charts/prime-api
    overrideValues: |
      image.tag=$(Build.BuildId)
    waitForCompletion: true
    install: true

- task: AzureCLI@2
  displayName: 'Wait until pod is running'
  inputs:
    azureSubscription: $(subscriptionId)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster)

      # Wait for pods to be in the Running state
      echo "Waiting for pods to be in 'Running' state..."
      kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=prime-api --timeout=45s
      if [ $? -eq 0 ]; then
        echo "Pods are in Running state!"
      else
        echo "Pods failed to reach Running state within timeout."
        exit 1
      fi